/** @format */
const {$importImage} = useNuxtApp();
export const gameList = {
  getData: () => {
    const data = [
      {
        value: 1,
        text: "财神到",
        en: "God Of Wealth",
        title: "V0030",
        roomId: "4000",
        url: "",
        src: $importImage("4000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "水牛",
        en: "Buffalo",
        title: "V0030",
        roomId: "4100",
        url: "",
        src: $importImage("4100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "埃及秘宝",
        en: "Arcane Egypt",
        title: "V0030",
        roomId: "4200",
        url: "",
        src: $importImage("4200_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "多福多财",
        en: "88 Fortune",
        title: "V0030",
        roomId: "4300",
        url: "",
        src: $importImage("4300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "富贵熊猫",
        en: "Fortune Panda",
        title: "V0030",
        roomId: "4400",
        url: "",
        src: $importImage("4400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "五龙争霸",
        en: "5 Dragons",
        title: "V0030",
        roomId: "4500",
        url: "",
        src: $importImage("4500_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "咆哮的荒野",
        en: "Roaring Wild",
        title: "V0030",
        roomId: "4600",
        url: "",
        src: $importImage("4600_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "白狮",
        en: "White Lion",
        title: "V0030",
        roomId: "4700",
        url: "",
        src: $importImage("4700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "忍者",
        en: "Go Ninja Go",
        title: "V0030",
        roomId: "4800",
        url: "",
        src: $importImage("4800_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "雪女",
        en: "Arctic Treasure",
        title: "V0030",
        roomId: "4900",
        url: "",
        src: $importImage("4900_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "圣诞",
        en: "Christmas wishes",
        title: "V0030",
        roomId: "5000",
        url: "",
        src: $importImage("5000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "魔术师",
        en: "Bling Bros Circus",
        title: "V0030",
        roomId: "5100",
        url: "",
        src: $importImage("5100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "挖矿",
        en: "Gold Rush",
        title: "V0030",
        roomId: "5200",
        url: "",
        src: $importImage("5200_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "小蜜蜂",
        en: "Bonus Bear",
        title: "V0030",
        roomId: "5300",
        url: "",
        src: $importImage("5300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Dolphins Nights",
        en: "Bonus Bear",
        title: "V0030",
        roomId: "5400",
        url: "",
        src: $importImage("5400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "大蓝鲸",
        en: "Great Blue",
        title: "V0030",
        roomId: "5500",
        url: "",
        src: $importImage("5500_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "公路之王",
        en: "Gold Highway",
        title: "V0030",
        roomId: "5600",
        url: "",
        src: $importImage("5600_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "嘉年华",
        en: "Carnival Cash",
        title: "V0030",
        roomId: "5700",
        url: "",
        src: $importImage("5700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "海盗",
        en: "Asgard Sails",
        title: "V0030",
        roomId: "5800",
        url: "",
        src: $importImage("5800_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "骑士",
        en: "War Of The Knights",
        title: "V0030",
        roomId: "5900",
        url: "",
        src: $importImage("5900_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "精灵女王",
        en: "Fairy Queen",
        title: "V0030",
        roomId: "6000",
        url: "",
        src: $importImage("6000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "经典水果机",
        en: "Jackpot Diamond",
        title: "V0030",
        roomId: "6100",
        url: "",
        src: $importImage("6100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "女巫",
        en: "Spooky Spinners",
        title: "V0030",
        roomId: "6200",
        url: "",
        src: $importImage("6200_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "公主",
        en: "The Jade Lotus 2",
        title: "V0030",
        roomId: "6300",
        url: "",
        src: $importImage("6300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "池塘",
        en: "Reel & Spin 2",
        title: "V0030",
        roomId: "6400",
        url: "",
        src: $importImage("6400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "城堡",
        en: "Castle Clash",
        title: "V0030",
        roomId: "6500",
        url: "",
        src: $importImage("6500_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "猫咪",
        en: "Meow Money",
        title: "V0030",
        roomId: "6600",
        url: "",
        src: $importImage("6600_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "斯巴达",
        en: "Rage Of Sparta",
        title: "V0030",
        roomId: "6700",
        url: "",
        src: $importImage("6700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "性感小魔鬼",
        en: "Sexy Devil",
        title: "V0030",
        roomId: "6800",
        url: "",
        src: $importImage("6800_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "火山",
        en: "Luck Volcano",
        title: "V0030",
        roomId: "6900",
        url: "",
        src: $importImage("6900_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "复活节岛",
        en: "Easter Island",
        title: "V0030",
        roomId: "7000",
        url: "",
        src: $importImage("7000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "玛雅帝国",
        en: "Mayan Empire",
        title: "V0030",
        roomId: "7100",
        url: "",
        src: $importImage("7100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "宙斯",
        en: "Zeus Wild",
        title: "V0030",
        roomId: "7200",
        url: "",
        src: $importImage("7200_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "迪斯科",
        en: "Disco Dolly",
        title: "V0030",
        roomId: "7300",
        url: "",
        src: $importImage("7300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "丛林女王",
        en: "Queen of jungle",
        title: "V0030",
        roomId: "7400",
        url: "",
        src: $importImage("7400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "齐天大圣",
        en: "Journey To The West",
        title: "V0030",
        roomId: "7600",
        url: "",
        src: $importImage("7600_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "开心农场",
        en: "Happy Farm 2",
        title: "V0030",
        roomId: "7700",
        url: "",
        src: $importImage("7700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "怪物",
        en: "Monster",
        title: "V0030",
        roomId: "7800",
        url: "",
        src: $importImage("7800_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "沙滩甜心",
        en: "Beach Sweetheart",
        title: "V0030",
        roomId: "7900",
        url: "",
        src: $importImage("7900_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "鱼跃龙门",
        en: "Dragon Gate",
        title: "V0030",
        roomId: "8000",
        url: "",
        src: $importImage("8000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "黑手党",
        en: "Mafia",
        title: "V0030",
        roomId: "8100",
        url: "",
        src: $importImage("8100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "花木兰",
        en: "Hua Mulan",
        title: "V0030",
        roomId: "8600",
        url: "",
        src: $importImage("8600_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "森林舞会",
        en: "Forest Ball",
        title: "V0030",
        roomId: "8700",
        url: "",
        src: $importImage("8700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "水浒传",
        en: "Water Margin",
        title: "V0030",
        roomId: "8800",
        url: "",
        src: $importImage("8800_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "三国",
        en: "Three Kingdom",
        title: "V0030",
        roomId: "8900",
        url: "",
        src: $importImage("8900_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "丰财聚宝",
        en: "Fortune Gold",
        title: "V0030",
        roomId: "9100",
        url: "",
        src: $importImage("9100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "丧尸国度",
        en: "Zombie Nation",
        title: "V0030",
        roomId: "9400",
        url: "",
        src: $importImage("9400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "烈火英雄",
        en: "Fire Hero",
        title: "V0030",
        roomId: "10000",
        url: "",
        src: $importImage("10000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "龙孵化",
        en: "Dragon Hatch",
        title: "V0030",
        roomId: "11000",
        url: "",
        src: $importImage("11000_pic", "png", "images/games"),
      },
      // {
      //   value: 1,
      //   text: "Safari King",
      //   en: "Safari King",
      //   title: "V0030",
      //   roomId: "11100",
      //   url: "",
      //   src: $importImage("11100_pic", "png", "images/games"),
      // },
      {
        value: 1,
        text: "玛雅消除",
        en: "Gonzo's Quest",
        title: "V0030",
        roomId: "12000",
        url: "",
        src: $importImage("12000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "雷神",
        en: "Gates of Olympus",
        title: "V0030",
        roomId: "12100",
        url: "",
        src: $importImage("12100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Sweet",
        en: "Sweet Bonanza",
        title: "V0030",
        roomId: "12300",
        url: "",
        src: $importImage("12300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Fortune Ox",
        en: "Fortune Ox",
        title: "V0030",
        roomId: "12400",
        url: "",
        src: $importImage("12400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Fortune Tiger",
        en: "Fortune Tiger",
        title: "V0030",
        roomId: "12500",
        url: "",
        src: $importImage("12500_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "幸运水果转盘",
        en: "Lucky Fruit Super Wheel",
        title: "V0030",
        roomId: "12700",
        url: "",
        src: $importImage("12700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "老鼠",
        en: "mouse",
        title: "V0030",
        roomId: "12900",
        url: "",
        src: $importImage("12900_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "巴西",
        en: "Mines",
        title: "V0030",
        roomId: "23600",
        url: "",
        src: $importImage("23600_pic", "png", "images/games"),
      },
      // {
      //   value: 1,
      //   text: "Double",
      //   en: "Double",
      //   title: "V0030",
      //   roomId: "23700",
      //   url: "",
      //   src: $importImage("23700_pic", "png", "images/games"),
      // },
      {
        value: 1,
        text: "Crash",
        en: "Crash",
        title: "V0030",
        roomId: "23800",
        url: "",
        src: $importImage("23800_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Aviator",
        en: "Aviator",
        title: "V0030",
        roomId: "24000",
        url: "",
        src: $importImage("4000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Penalty",
        en: "Penalty",
        title: "V0030",
        roomId: "27100",
        url: "",
        src: $importImage("27100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "转盘",
        en: "RODA DA SORTE",
        title: "V0030",
        roomId: "27200",
        url: "",
        src: $importImage("27200_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Dice",
        en: "DICE",
        title: "V0030",
        roomId: "27300",
        url: "",
        src: $importImage("27300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "LuckyPool",
        en: "BOLA DA SORTE",
        title: "V0030",
        roomId: "27400",
        url: "",
        src: $importImage("27400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "RealRoulette",
        en: "Roleta Real",
        title: "V0030",
        roomId: "27500",
        url: "",
        src: $importImage("27500_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Truco",
        en: "Truco",
        title: "V0030",
        roomId: "27600",
        url: "",
        src: $importImage("27600_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Keno",
        en: "Keno",
        title: "V0030",
        roomId: "27700",
        url: "",
        src: $importImage("27700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Thimbles",
        en: "Thimbles",
        title: "V0030",
        roomId: "27800",
        url: "",
        src: $importImage("27800_pic", "png", "images/games"),
      },
      // {
      //   value: 1,
      //   text: "Soccer_Babes",
      //   en: "GAROTAS DE FUTEBOL",
      //   title: "V0030",
      //   roomId: "27900",
      //   url: "",
      //   src: $importImage("27900_pic", "png", "images/games"),
      // },
      {
        value: 1,
        text: "RedBlackPoker",
        en: "Vermelho Preto Poker",
        title: "V0030",
        roomId: "28000",
        url: "",
        src: $importImage("28000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "CrazyDice",
        en: "Crazy Dice",
        title: "V0030",
        roomId: "28100",
        url: "",
        src: $importImage("28100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "WheelOfSky",
        en: "Roda Do Ceu",
        title: "V0030",
        roomId: "28200",
        url: "",
        src: $importImage("28200_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "RodaDaFortuna",
        en: "Roda da Fortuna",
        title: "V0030",
        roomId: "28300",
        url: "",
        src: $importImage("28300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "LuckyDice",
        en: "Dados Da Sorte",
        title: "V0030",
        roomId: "28400",
        url: "",
        src: $importImage("28400_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "HILO",
        en: "HILO",
        title: "V0030",
        roomId: "28500",
        url: "",
        src: $importImage("28500_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "MagicWheel",
        en: "Magic Wheel",
        title: "V0030",
        roomId: "28600",
        url: "",
        src: $importImage("28600_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "CrazyThimbles",
        en: "Crazy Thimbles",
        title: "V0030",
        roomId: "28700",
        url: "",
        src: $importImage("28700_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Baccarat",
        en: "Baccarat",
        title: "V0030",
        roomId: "28800",
        url: "",
        src: $importImage("28800_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Plinko",
        en: "Plinko",
        title: "V0030",
        roomId: "28900",
        url: "",
        src: $importImage("28900_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Limbo",
        en: "Limbo",
        title: "V0030",
        roomId: "29000",
        url: "",
        src: $importImage("29000_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Video Poker",
        en: "Video Poker",
        title: "V0030",
        roomId: "29100",
        url: "",
        src: $importImage("29100_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "Spin And Win",
        en: "Spin And Win",
        title: "V0030",
        roomId: "29300",
        url: "",
        src: $importImage("29300_pic", "png", "images/games"),
      },
      {
        value: 1,
        text: "FortuneTigerGF",
        en: "FortuneTigerGF",
        title: "V0030",
        roomId: "32500",
        url: "",
        src: $importImage("29300_pic", "png", "images/games"),
      },
    ];
    return data;
  },
};
